### PR TITLE
FC-45 ::

### PR DESCRIPTION
**Pull request by cfmitrah**
- Disable alias name.

### CODE REVIEW

**Comment by cfmitrah** [comment]
I've fixed the issue mentioned in https://farcry.jira.com/browse/CMS-45. Please check that & let us know anything needed.

Thanks

**Comment by cfmitrah** [comment]
@justincarter Reminder for review :)

**Comment by shib71** [comment]
This change will disable the field for _any_ navigation object that has an alias set. In practice, the field should only be disabled if it is set to one of the values FarCry depends on.

**Comment by justincarter** [comment]
Instead of making this change in the generic "field" formtool we should probably customise the dmNavigation edit handler to override the behaviour of the `lNavIDAlias` field so that it's disabled when the value matches the built-in nav aliases used by core (root, home, hidden, rubbish are the main ones). I'll close this PR.

**Comment by justincarter** [comment]
For reference, this was the eventual solution, to override the edit method of the `lNavIDAlias` property ub `dmNavigation`;

https://github.com/farcrycore/core/commit/8806c9465aa93cbe19ec9ad8d236a6f8e76b6d4c

**Pull request closed without merging**
