### PR TITLE
wrong variable name, causes an error to be thrown

### PR DESCRIPTION
**Pull request by seancoyne**

### CODE REVIEW

**Comment by justincarter** [comment]
This one seems like an engine compatibility issue, ACF uses "result" and Railo/Lucee uses "returnvariable". We'll need to do a fix that supports both.

**Comment by justincarter** [comment]
For reference:
https://cfdocs.org/cfschedule
http://docs.lucee.org/reference/tags/schedule.html
https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-r-s/cfschedule.html

**Comment by seancoyne** [comment]
Sounds like a Railo/Lucee bug to me.  It's been there since CF10 for which they claim compatibility.

I'll re-implement a fix for both engines.

**Comment by seancoyne** [comment]
@justincarter this commit will handle either engine

**Comment by justincarter** [comment]
Thanks Sean, much appreciated!

**Pull request merged**
