### PR TITLE
FC-3137: COAPI manager shows pending changes for datetime fields when using MS SQL 2012+

### PR DESCRIPTION
**Pull request by jeffcoughlin**
When using MSSQL 2012+ the user receives a pending option to deploy changes to date fields (like datetimecreated) where null is allowed. The error is because the default property is set to blank and the code in MSSQLGateway.cfc has a condition that conflicts with it. Fix provided in a pull request.

### CODE REVIEW

**Comment by seancoyne** [comment]
this bug is pretty annoying.  would be nice to get this merged ASAP

**Comment by justincarter** [comment]
@jeffcoughlin Would you be able to provide steps to reproduce the problem and/or a test case with sample code (particularly the formtool properties in question)? I can't reproduce any issue with pending changes/conflicts on the COAPI page for datetime fields with the MSSQL2012 DB gateway, or other DB gateways, so there must be some combination of formtool attributes or database state that I'm missing.

The reason I'm reviewing in detail is because this code is originally from the MSSQL DB gateway (which is effectively gateways for 2000/2005/2012), and it's also identical to the MySQL gateway; so if there is a problem it seems like it may need to be fixed in both of those places to cover all bases.

Ordinarily a column that allows nulls (i.e. required="false") should enter into the first part of the below if statement because `arguments.schema.nullable` should be true;

```
<cfif (arguments.value eq "" or arguments.value gt dateadd("yyyy",100,now()) or arguments.value eq "1 January 2050" or arguments.value eq "NULL") and arguments.schema.nullable>
	<cfset stResult.null = true />
	<cfset stResult.value = "" />
<cfelseif arguments.value eq "" or arguments.value gt dateadd("yyyy",100,now()) or arguments.value eq "1 January 2050" or arguments.value eq "NULL">
	<cfset stResult.value = dateadd('yyyy',200,now()) />
<cfelse>
	<cfset stResult.value = arguments.value />
</cfif>
```

It seems like if the execution was mistakenly entering into the `elseif` block then it's because there is an issue related to `arguments.schema.nullable` not being set correctly. Changing the condition on the `elseif` block might affect older projects that are being upgraded, so perhaps there's either a root cause related to `arguments.schema.nullable` or something else that you're experiencing.

cheers,
Justin

**Comment by jeffcoughlin** [comment]
I'll do you one better and just explain what's happening.

FourQ is setting all default date values to 200 years in the future even though everyone is setting it to blank (explained below).

To replicate: If you set your dbType to "mssql2012" in your farcryConstructor then FourQ changes all the datetime fields to datetime2. datetime2 correctly allows a blank value for the default value (which is what everyone uses in most cases for their date fields - including datetimeCreated and datetimeUdpated fields on every content type set by FarCry). However the code in that method doesn't allow you to set it to blank and instead forces the default date to 2200 years in the future. That I can work around, but every time you go into the COAPI manager is lists hundreds of conflicts that need to be fixed to change the date to blank. If you tell it to fix it, it sets it to 200 years in the future from the time you click "fix"). It does all this unless the field is nullable (yes, that makes no sense to me either). I would have taken that part out of the condition (in the original getValueForDB() function), but I wasn't sure if that would cause any backwards compatibility issues with older versions of SQL (and I don't really care to test a bunch of SQL platforms that I no longer support). Instead I just copied the method into MSSQL2012Gateway.cfc and modified it to *not* set the date to 200 years in the future when the user is specifically trying to set it to blank.

Are there better ways to do this? Yes. But it's been so annoying the past couple years and I spent too many hours trying to track it down that when I finally did I just put in a quick patch and was happy to see FarCry stop complaining and allow our team to deploy COAPI changes like normal again instead of going through each COAPI type line-by-line each time.

I hope that made sense. It's late here :)

**Comment by jeffcoughlin** [comment]
Did that make sense?

**Comment by jeffcoughlin** [comment]
Did you have any other questions? Should I push the same change again since it fixes the problem of FarCry inserting bad data into all of our tables?

**Comment by justincarter** [comment]
No further questions, I just haven't had time to retest yet. I should get
to it on Thursday or Friday!

**Comment by jeffcoughlin** [comment]
So I ran into a bug recently with this modification where if I save a blank value for something like expiry date, it was giving a generic java error. For now I've removed this custom code/method and am manually running a script to set the default value to blank every time I create a new date field on any table (otherwise the error in COAPI is maddenly annoying). This workaround sucks and is time consuming, but its better than nothing until a real fix os found. What ideas do you have to help battle this?

**Comment by jeffcoughlin** [comment]
Any luck with this yet? Does anyone else use MSSQL (since this problem happens to all MSSQL setups)? Should we move to a different SQL platform?

**Comment by justincarter** [comment]
We use MSSQL for a good portion of clients, I don't think you need to switch platforms :)

As I mentioned before, I can't reproduce any issue with pending changes/conflicts on the COAPI page for datetime fields with the MSSQL2012 DB gateway, or other DB gateways, so there must be some combination of formtool attributes or database state that I'm missing.

If you can provide a simple content type to reproduce the problem -- even if it just has 1 single date property -- then I can drop it into an app and test it.

**Comment by jeffcoughlin** [comment]
To reproduce, create a simple content type (just give it a title field or something). Deploy. You’ll see all the annoying error messages in the COAPI manager. That’s it.

If you want to see hundreds of errors like we have for all of our clients, create many content types :)

Jeff

**Comment by justincarter** [comment]
I've done that and the problem doesn't appear... There are no COAPI conflicts relating to datetime fields.

**Comment by jeffcoughlin** [comment]
Hmm...

Did you remember to set this.dbType = "mssql2012"; in your farcryConstructor.cfm? (and update app)

**Comment by justincarter** [comment]
Of course :)

**Comment by jeffcoughlin** [comment]
Okay, I just created the following type and I get the conflict.

#### testType.cfc:
```
component extends = "farcry.core.packages.types.types" displayname = "Test Type" {

	property name = "title" type = "nstring" required = true default = "" dbNullable = false
		ftSeq = 110 ftLabel = "Title" ftDefault = "" bLabel = true
		ftFieldset = "Details" ftValidation = "required"
		ftType = "string";

}
```

After deploying the type the COAPI manager will say that there are conflicts that need to be resolved. The conflicts will be on date fields (in this example dateTimeCreated and dateTimeUpdated).

When you click on the `Resolve Conflicts` link and then hover over the fieldname in question you'll see something similar to the following:
```
type		datetime		=> datetime
default		2218-08-17T02:54:54	=>
nullable	false			=> NO
precision	3			=> 3
```

**Comment by justincarter** [comment]
Here's a screenshot of the database tables with the `datetime2` columns deployed;

image

Here's a screenshot of the COAPI page with no schema conflicts;

image

The `farcryConstructor.cfm` has;
```
<cfset THIS.dsn = "fandango" /> 
<cfset THIS.dbType = "mssql2012" /> 
<cfset THIS.dbOwner = "dbo." /> 
```

This is on Lucee 5.1 with the Microsoft SQL driver (`com.microsoft.sqlserver.jdbc.SQLServerDriver`). I could update to Lucee 5.2 but that will likely be the same.

Which CFML engine and SQL driver are you using? Perhaps that could be a factor?

In the output you've posted, it says "nullable NO" -- that seems to be a problem, because nullable should be "true".

**Comment by jeffcoughlin** [comment]
I'm using ACF. I've recreated it on ACF2016 and ACF2018 and on a few flavors of MSSQL (including the latest). I'm using the default driver (labeled `Microsoft SQL Server`) that comes with ACF.

**Comment by jeffcoughlin** [comment]
I'm trying to remember what versions of SQL my clients are using that have this error (they are scattered versions).  I am currently testing this on SQL 2016 and SQL 2017. I "think" one of my clients who gets this error is using MSSQL 2012, but it could be 2014. Anyway, I'm not sure if that is a potential factor.

Using the code sample I posted earlier, here is the date field info. Notice the `Allow Nulls` and `Default Value or Binding`. One way we've been currently getting around this error is to edit every date field and manually set the `Default Value or Binding` to blank.

image

**Comment by justincarter** [comment]
For my own notes, if it is related to the use of `INFORMATION_SCHEMA.columns`, then perhaps we can consider a change to using `sys.columns` (further reading required on my part);
https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-columns-transact-sql?view=sql-server-2017

My tests are on SQL2014. I can test SQL2016 next week.

In the meantime the more specific version info you can give us, including testing the above query, would help narrow it down further.

**Comment by jeffcoughlin** [comment]
I'll run that query and check. I noticed that your datetimelastupdated also says NO for IS_NULLABLE

**Comment by jeffcoughlin** [comment]
The version I am running this particular code on tonight is SQL 2016 (SP2).  I remember seeing the same error in SP1, but don't recall if it happened before SP1.

image

**Comment by justincarter** [comment]
The reviewDate column is nullable with a default value of NULL, and the
others and not nullable but they have a default value far in the future.
Those are the two cases the columns need to satisfy for the frameworks
nullable support to function correctly. So in my case both of those are
working fine.

I'll look again next week and test SQL2016. I'll also try removing the
defaults manually and see if that puts it into a broken state that cannot
be repaired.

**Comment by justincarter** [comment]
I've tested on SQL2016 (RTM-GDR) and there are no schema conflicts;

image

Schema seems fine for reviewData (nullable, default NULL), datetimelastupdated and datetimecreated  (not nullable, default 2216-...)

image

I'm not sure if the issue could be 2016 SP1 or SP2 related but I don't have either to test with at the moment.

One thing about your last screenshot does seem to stand out, the datetimelastupdated and datetimecreated columns say the default is NULL but the column is not nullable?

image

Can you try putting the old defaults back and see if that resolves the COAPI schema conflicts? (e.g. `2216-09-26 14:59:01`)

**Comment by seancoyne** [comment]
Fixing the default manually removes the COAPI conflicts.  That is the whole issue though.  Why is FC not setting the correct default?  I've seen this with many client sites both in development VMs and on production servers. We use the p720 branch, ACF 11, 2016 & 2018, SQL Server 2014, 2016 & 2017.

The only combination I've seen recently that does not show this behavior is ACF 2018 & SQL 2017.  We're building a brand new site now and in development, when I've created new content types I have yet to run into it.

You keep showing screenshots of dmHTML.  Have you created a new content type and tested? I've found that the default content types that are created by the installer are created correctly, but new content types deployed with the COAPI tool are the ones with the issue.

**Comment by jeffcoughlin** [comment]
> Have you created a new content type and tested?

I assume he did with the requested code sample I gave him to recreate the problem. Maybe he missed it in all the chatter?

**Comment by justincarter** [comment]
I've deployed Jeff's example content type and it deploys correctly, there are no schema conflicts after deployment;

coapi-1

coapi-2

image

How did the default values go missing, was it a manual change?

FarCry supports "null dates" with two scenarios;
- If the column is not nullable then it expects a default date far in the future -- not a default of NULL
- If the column is nullable, then it expects a default of NULL

I'm guessing that a manual change could have put it into a state where it can't be fixed.

For a single one of your broken datetime properties in a single content type, can you try to deploy the schema change and enable the debug option so that we can see the SQL that is being run? It might show the reason the schema change can't be deployed.

**Comment by jeffcoughlin** [comment]
Sure. For the same **Test Type** content type, I attempted to repair the **dateTimeCreated** field. To play it safe, I also just updated to the latest p720 and restarted ACF before testing anything (make sure we're on the same page for my test - I was be a few weeks behind on p720. I still got the same error/conflic though).

image

**Comment by justincarter** [comment]
Ok, so this says it set the `datetimecreated` to NOT NULL, with a default of `2218-08-20 20:39:37`, and there was no errors... If you run the schema query, what results does it give?

```
select 		*
from		information_schema.columns
where		table_name='testType'
```

**Comment by jeffcoughlin** [comment]
image

**Comment by justincarter** [comment]
Can you also post the result of the query I pasted above?

**Comment by jeffcoughlin** [comment]
image

**Comment by jeffcoughlin** [comment]
Do you mean MSSQL2005?

**Comment by justincarter** [comment]
That's the one :)

**Comment by jeffcoughlin** [comment]
If I do, I don't know what will happen to all the datetime fields if I roll them back from datetime2 to datetime (since that is pretty much the major difference). But I'm pretty sure this error does not show up. I haven't tested in MSSQL 2016 - which is what I'm currently using, but I'm guessing the error won't exist there either.

**Comment by justincarter** [comment]
Just to summarize my testing, so far I've used Lucee 5.1, with the MSSQL2012 DB gateway, on SQL 2012, 2014, and 2016 (RTM, not SP1 or SP2), and so far I'm unable to reproduce the issue at all.

This makes me think the issue is only surfacing on ACF 2016/2018 -- unless you've also see it happen on older ACF versions?

**Comment by jeffcoughlin** [comment]
Okay, this is interesting. I just verified another client with the same problem. They have several sites running on that server, but I checked two of them (and both had the problem). One is running FC 7.2.10 (a new site from a month ago) and the other is 6.3.2 (a much older site).

Server specs are: SQL 2014, ACF 11.

The interesting part is that FC 6.3.2 doesn't even have the mssql2012 gateway in it. So this site is running the mssql2005 dbgateway.

I could be wrong, but I believe when the dbgateway stuff was updated to support 20012, the root mssqlGateway.cfc was also updated. I wonder if it was pushed to FC6 as well (just a thought).

Also, in case I never mentioned it: This only affects new datetime fields that are deployed after some point in time within the last couple years (I don't recall when). So, at some point the problem started happening (I'm guessing around the time the mssql2012 gateway was released). But it only started affecting new datetime fields that were deployed after that time (all existing datetime field at the time have still never shown a problem to this day). Also, if we manually set the default value to blank in the database, the error goes away as well (that part I mentioned many posts ago - I'm just repeating it here in case it is relevant).

**Comment by justincarter** [comment]
The `getValueForDB` method is from the base MSSQLGateway, so if the cause is some external factor then it makes sense that there could be an issue when using either MSSQL2005Gateway or MSSQL2012Gateway (or older versions of core which don't contain MSSQL2012Gateway). The `<cfcase value="datetime">` block in that method is actually the same for both MSSQLGateway and MySQLGateway, which means all DB gateways regardless of the specific engine version are using the same logic.

Since you are able to reproduce the error on ACF 11 then I should be able to jump in and do a test install on that with the test content type later today.

**Pull request merged**
